apiVersion: project.spikeidp.cit.com/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/project
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Managed by Terraform
    features:
      artifacts: disabled
      testplans: disabled
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
