apiVersion: azure-devops.spikeidp.cit.com/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: bradesco-seguros-azure-devops
      namespace: crossplane-system
      key: credentials
