apiVersion: gitrepository.spikeidp.cit.com/v1alpha1
kind: Repository
metadata:
  annotations:
    meta.upbound.io/example-id: gitrepository/v1alpha1/repository
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    initialization:
    - initType: Clean
    name: Example Empty Git Repository
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: project.spikeidp.cit.com/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: gitrepository/v1alpha1/repository
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
